name: 'Terraform Action'
description: 'This is for terraform'
inputs:
  terraform_directory:
    description: 'The working directory of the Terraform to deploy'
    required: true
    default: 'terraform'
runs:
  using: 'composite'
  steps:
    - run: terraform init -input=false
      shell: bash
      working-directory: ./${{ inputs.terraform_directory }}
    - run: bash ${{github.action_path}}/scripts/terraform-plan.sh
      shell: bash
      working-directory: ./${{ inputs.terraform_directory }}

