name: 'Terraform Action'
description: 'This is for terraform'
inputs:
  terraform-directory:
    description: 'The working directory of the Terraform to deploy'
    required: true
    default: 'terraform'
runs:
  using: 'composite'
  steps:
    - run: terraform init
      shell: bash
    - run: terraform plan 
      shell: bash

